baseURL = "https://datarekrutt.netlify.com/"
DefaultContentLanguage = "no"
languageCode = "en-us"
title = "DataRekrutt"
theme = "capsule"
SectionPagesMenu = "main"
canonifyURLs = true
enableGitInfo = true
enableRobotsTXT = true
[params]
  repo = "https://github.com/hackingjack/hugo-datarekrutt.git"
  share = true
  searchURL = "https://google.com"

